// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdwikzwkgfjsrqgnfuem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkd2lrendrZ2Zqc3JxZ25mdWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTg2NTYsImV4cCI6MjA2Njg5NDY1Nn0.BM0aj7wESO3iLrVVQEHQlLzVV7OH7ouiX9QaBjUYLSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});